apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app-staging
resources:
  - ../../base
images:
  - name: ghcr.io/esarath/sample-app
    newTag: "e132cfe"
patches:
  - target:
      kind: Deployment
      name: sample-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: sample-app-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: staging
      - op: replace
        path: /data/APP_VERSION
        value: "e132cfe"
