apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: 1536Mi
    limits.cpu: "3"
    limits.memory: 3Gi
    pods: "15"
    persistentvolumeclaims: "10"
    services: "15"
    configmaps: "30"
    secrets: "30"
    count/deployments.apps: "15"
