apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis-app-deployment.yaml
  - redis-app-service.yaml
  - redis-db-statefulset.yaml
  - redis-db-service.yaml
  - redis-db-hpa.yaml
  - redis-db-pdb.yaml
