apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-db
  namespace: stage
spec:
  serviceName: redis-db
  replicas: 1
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
        - name: redis-db
          image: docker.io/bitnamilegacy/redis:7.2.5-debian-12-r6
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-stage-auth
                  key: redis-password
            - name: REDIS_AOF_ENABLED
              value: "yes"
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 250m, memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            runAsNonRoot: true
            seccompProfile: { type: RuntimeDefault }
          volumeMounts:
            - name: data
              mountPath: /bitnami/redis/data
          livenessProbe:
            exec:
              command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "--no-auth-warning", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-storage
        resources: { requests: { storage: 2Gi } }
