apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openshift-gitops-controller-pdb
  namespace: openshift-gitops
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-gitops-application-controller
