apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app-production
resources:
  - ../../base
images:
  - name: ghcr.io/esarath/sample-app
    newTag: "0a96677"
patches:
  - target:
      kind: Deployment
      name: sample-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: sample-app-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
      - op: replace
        path: /data/APP_VERSION
        value: "0a96677"
