apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "tenant-namespace.name" . }}-limits
  namespace: {{ include "tenant-namespace.name" . }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.containerDefaultCpu | quote }}
        memory: {{ .Values.limitRange.containerDefaultMemory | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.containerDefaultRequestCpu | quote }}
        memory: {{ .Values.limitRange.containerDefaultRequestMemory | quote }}
      max:
        cpu: {{ .Values.limitRange.containerMaxCpu | quote }}
        memory: {{ .Values.limitRange.containerMaxMemory | quote }}
      min:
        cpu: {{ .Values.limitRange.containerMinCpu | quote }}
        memory: {{ .Values.limitRange.containerMinMemory | quote }}
