apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "tenant-namespace.name" . }}
  labels:
    {{- if .Values.argocdManaged }}
    argocd.argoproj.io/managed-by: openshift-gitops
    {{- end }}
    app.kubernetes.io/part-of: multi-tenancy
    tenant-environment: {{ .Values.tenant.environment }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    openshift.io/description: {{ .Values.tenant.description | quote }}
    openshift.io/display-name: {{ .Values.tenant.name | quote }}
