apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "tenant-namespace.name" . }}-quota
  namespace: {{ include "tenant-namespace.name" . }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    pods: {{ .Values.quota.pods | quote }}
    persistentvolumeclaims: {{ .Values.quota.pvcs | quote }}
    services: {{ .Values.quota.services | quote }}
    configmaps: {{ .Values.quota.configmaps | quote }}
    secrets: {{ .Values.quota.secrets | quote }}
