apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-gitops-server-metrics
  namespace: openshift-gitops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-gitops-server
  endpoints:
    - port: https
      interval: 30s
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
