apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-prod
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: multi-tenancy
    environment: prod
spec:
  project: multi-tenancy
  source:
    repoURL: https://github.com/esarath/ocp-gitops-poc.git
    targetRevision: main
    path: platform/multi-tenancy/base/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
